#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x01FA998FBAC6374A (stub@ubuntu.com)
#
Name     : deprecated-pytz
Version  : 2018.9
Release  : 61
URL      : https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz
Source99 : https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz.asc
Summary  : World timezone definitions, modern and historical
Group    : Development/Tools
License  : MIT
Requires: deprecated-pytz-license = %{version}-%{release}
Requires: deprecated-pytz-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-dev

%description
pytz - World Timezone Definitions for Python
============================================

%package legacypython
Summary: legacypython components for the deprecated-pytz package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pytz package.


%package license
Summary: license components for the deprecated-pytz package.
Group: Default

%description license
license components for the deprecated-pytz package.


%package python
Summary: python components for the deprecated-pytz package.
Group: Default

%description python
python components for the deprecated-pytz package.


%prep
%setup -q -n pytz-2018.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554327443
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pytz
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-pytz/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pytz/LICENSE.txt

%files python
%defattr(-,root,root,-)
